### Single Layer Neuron

In [1]:
# Create model class

import torch
import torch.nn as nn


class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out


In [2]:
# create dataset
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])

#call model for forward pass
# model.forward(features)

model(features)

tensor([[0.4812],
        [0.4744],
        [0.4444],
        [0.4280],
        [0.4468],
        [0.5174],
        [0.4927],
        [0.4958],
        [0.4326],
        [0.4729]], grad_fn=<SigmoidBackward0>)

In [3]:
model.linear.weight

Parameter containing:
tensor([[ 0.1542,  0.4129, -0.0017, -0.3305,  0.0481]], requires_grad=True)

In [4]:
model.linear.bias

Parameter containing:
tensor([-0.2860], requires_grad=True)

### Addding hidden layer

In [5]:
# Create model class

import torch
import torch.nn as nn


class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out


In [6]:
# create dataset
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])

#call model for forward pass
# model.forward(features)

model(features)

tensor([[0.5745],
        [0.5674],
        [0.5452],
        [0.4834],
        [0.5893],
        [0.5709],
        [0.5479],
        [0.5445],
        [0.5344],
        [0.5253]], grad_fn=<SigmoidBackward0>)

In [7]:
model.linear1.weight

Parameter containing:
tensor([[ 0.0452,  0.1554, -0.2387, -0.1957, -0.3133],
        [ 0.3764,  0.4340, -0.3924,  0.4030, -0.2600],
        [ 0.2214, -0.0664,  0.0377, -0.0729, -0.0516]], requires_grad=True)

In [8]:
model.linear2.weight

Parameter containing:
tensor([[ 0.1468, -0.4771,  0.0834]], requires_grad=True)

In [9]:
pip install torchinfo


In [10]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

###  Adding sequential container

In [11]:
# Create model class

import torch
import torch.nn as nn


class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
    )


  def forward(self,features):

    out = self.network(features)

    return out


In [12]:
# create dataset
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])

#call model for forward pass
# model.forward(features)

model(features)

tensor([[0.3218],
        [0.3182],
        [0.3541],
        [0.3394],
        [0.3300],
        [0.3423],
        [0.3267],
        [0.3456],
        [0.3430],
        [0.3233]], grad_fn=<SigmoidBackward0>)